version: '3'
services:

  pg:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - ./db/:/docker-entrypoint-initdb.d/
    
    environment:
    - POSTGRES_PASSWORD=example
    - POSTGRES_USER=sportsmans_user
    - POSTGRES_DB=sportmans_db
     
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080